stages:
  - test

rust-latest:
  stage: test
  image: rust:latest
  script:
    - apt update -qq
    - apt-get -qq install pkg-config libssl-dev protobuf-compiler
    - cargo test --verbose

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  script:
    - apt update -qq
    - apt-get -qq install pkg-config libssl-dev protobuf-compiler
    - cargo test --verbose
  allow_failure: true